name: CodexBarMobile
options:
  bundleIdPrefix: com.codexbar
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "26.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    ENABLE_UPCOMING_FEATURE_STRICT_CONCURRENCY: true

targets:
  CodexBarSync:
    type: framework
    platform: iOS
    sources:
      - path: ../Shared
        group: Shared
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.codexbar.sync
        GENERATE_INFOPLIST_FILE: true

  CodexBarMobile:
    type: application
    platform: iOS
    sources:
      - path: CodexBarMobile
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: CodexBarSync
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.codexbar.mobile
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        CODE_SIGN_ENTITLEMENTS: CodexBarMobile/CodexBarMobile.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_EMIT_LOC_STRINGS: true
    info:
      path: CodexBarMobile/Info.plist
      properties:
        UILaunchScreen: {}
    entitlements:
      path: CodexBarMobile/CodexBarMobile.entitlements

  CodexBarMobileTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: CodexBarMobileTests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: CodexBarMobile
      - target: CodexBarSync
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.codexbar.mobile.tests
        GENERATE_INFOPLIST_FILE: true
